### ISSUE TITLE
WCF and TCP protocol

### ISSUE THREAD

**Issue by rd0707** [raid-teyar/Smart_Home#1]
why exactly you are using TCP protocol for communication and not just standard HTTP ?

**Comment by raid-teyar** [comment]
I definitely could go with HTTP, but I wanted something that can easily maintain a session connection.
Also since the System is only going to run locally (the house) i didn't see a good reason to use HTTP.

**Comment by raid-teyar** [comment]
i am gonna close this one, feel free to open again
